// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bakery.Data;

#nullable disable

namespace bakery.Data.Migrations
{
    [DbContext(typeof(BakeryContext))]
    [Migration("20241203041702_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("bakery.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A classic apple pie with a flaky crust and a hint of cinnamon.",
                            ImageName = "apple_pie.jpg",
                            Name = "Apple Pie",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "A rich and decadent chocolate cake with layers of chocolate frosting.",
                            ImageName = "chocolate_cake.jpg",
                            Name = "Chocolate Cake",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "A moist and fluffy blueberry muffin bursting with fresh blueberries.",
                            ImageName = "blueberry_muffin.jpg",
                            Name = "Blueberry Muffin",
                            Price = 3.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
