@host=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6MSwiaWF0IjoxNzI5NDMyMjcxLCJleHAiOjE3MzgwNzIyNzF9.ialKgloQjY9eSYMFA3pahQgdqIVNUwMKuEcR6Wxm7_s


###
POST {{host}}/api/users/register
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

###
POST {{host}}/api/users/login
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

### 
GET {{host}}/ HTTP/1.1

###
GET {{host}}/ HTTP/1.1
Authorization:Bearer {{token}}

